blogDB: &blogDB
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: tmello
  password:
  host: localhost

development:
  <<: *blogDB
  database: blog_development

test:
  <<: *blogDB
  database: blog_test

production:
  <<: *blogDB
  database: blog_production
